/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        'on-secondary-fixed-variant': '#6e3900',
        'secondary-container': '#fe932c',
        'surface': '#f8f9ff',
        'on-primary-fixed': '#131b2e',
        'secondary-fixed-dim': '#ffb77d',
        'primary-fixed-dim': '#bec6e0',
        'on-primary-fixed-variant': '#3f465c',
        'outline': '#76777d',
        'inverse-on-surface': '#eaf1ff',
        'primary': '#f2320c',
        'on-primary': '#ffffff',
        'primary-container': '#0b1c30',
        'on-primary-container': '#ffffff',
        'secondary': '#0b1c30',
        'on-secondary': '#ffffff',
        'secondary-container': '#13253b',
        'on-secondary-container': '#ffffff',
        'tfhc-red': '#f2320c',
        'tfhc-navy': '#0b1c30',
        'brand-red': '#f2320c',
        'brand-navy': '#0b1c30',
        indigo: {
          50: '#fff1ee',
          100: '#ffe1db',
          200: '#ffc6bc',
          300: '#ffa090',
          400: '#f8664b',
          500: '#f2320c',
          600: '#f2320c',
          700: '#d82a08',
          800: '#b22206',
          900: '#831f0c',
          950: '#460b02',
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-lg': '24px',
        'stack-md': '16px',
        gutter: '12px',
        'section-gap': '32px',
        'edge-margin': '16px',
        safe: 'env(safe-area-inset-bottom)',
      },
      fontFamily: {
        'headline-md': ['var(--font-inter)', 'sans-serif'],
        'headline-lg': ['var(--font-inter)', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'sans-serif'],
        'label-sm': ['var(--font-inter)', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'sans-serif'],
        'headline-sm': ['var(--font-inter)', 'sans-serif'],
        'label-md': ['var(--font-inter)', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
