/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        'on-secondary-fixed-variant': '#6e3900',
        'secondary-container': '#fe932c',
        'surface': '#f8f9ff',
        'on-primary-fixed': '#131b2e',
        'secondary-fixed-dim': '#ffb77d',
        'primary-fixed-dim': '#bec6e0',
        'on-primary-fixed-variant': '#3f465c',
        'outline': '#76777d',
        'inverse-on-surface': '#eaf1ff',
        'primary': '#000000',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'inverse-primary': '#bec6e0',
        'tertiary': '#000000',
        'tertiary-container': '#002113',
        'secondary-fixed': '#ffdcc3',
        'on-background': '#0b1c30',
        'on-tertiary-fixed-variant': '#005236',
        'outline-variant': '#c6c6cd',
        'surface-container-low': '#eff4ff',
        'on-secondary-container': '#663500',
        'on-tertiary-fixed': '#002113',
        'on-surface': '#0b1c30',
        'surface-container-high': '#dce9ff',
        'primary-fixed': '#dae2fd',
        'surface-tint': '#565e74',
        'on-tertiary-container': '#009668',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'error': '#ba1a1a',
        'primary-container': '#131b2e',
        'surface-container-highest': '#d3e4fe',
        'secondary': '#904d00',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#2f1500',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-surface-variant': '#45464d',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#213145',
        'background': '#f8f9ff',
        'tertiary-fixed': '#6ffbbe',
        'surface-container': '#e5eeff',
        'on-primary-container': '#7c839b',
        'surface-variant': '#d3e4fe',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-lg': '24px',
        'stack-md': '16px',
        gutter: '12px',
        'section-gap': '32px',
        'edge-margin': '16px',
        safe: 'env(safe-area-inset-bottom)',
      },
      fontFamily: {
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
