import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { MeetingStatus, MemberStatus, WeeklyAvailabilityState } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';

@Injectable()
export class AvailabilityService {
  constructor(private readonly prisma: PrismaService) {}
  private weekStart(now = new Date()) { const tz = process.env.TFHC_TIMEZONE || 'Africa/Lagos'; const p = new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',weekday:'short'}).formatToParts(now); const val=(t:string)=>Number(p.find(x=>x.type===t)?.value); const weekday=p.find(x=>x.type==='weekday')?.value; const date=new Date(Date.UTC(val('year'),val('month')-1,val('day'))); date.setUTCDate(date.getUTCDate()-({Mon:0,Tue:1,Wed:2,Thu:3,Fri:4,Sat:5,Sun:6}[weekday ?? 'Mon'])); return date; }
  async openCurrentWeek(now = new Date()) { const weekStart=this.weekStart(now); const closesAt=new Date(now.getTime()+24*60*60*1000); return this.prisma.weeklyAvailabilityCycle.upsert({where:{weekStart},update:{},create:{weekStart,opensAt:now,closesAt}}); }
  async currentForMember(memberId: string) { const cycle=await this.prisma.weeklyAvailabilityCycle.findUnique({where:{weekStart:this.weekStart()},include:{commitments:{where:{memberId}},responses:{where:{memberId}}}}); if(!cycle) throw new NotFoundException('Weekly availability has not opened'); const meetings=await this.weekMeetings(cycle.weekStart); return {cycle:{id:cycle.id,state:cycle.state,opensAt:cycle.opensAt,closesAt:cycle.closesAt},meetings,selectedMeetingIds:cycle.commitments.filter(x=>x.status==='COMMITTED').map(x=>x.meetingId),submitted:cycle.responses.length>0}; }
  async submit(memberId: string, meetingIds: string[]) { if(!Array.isArray(meetingIds)||meetingIds.some(x=>typeof x!=='string')||new Set(meetingIds).size!==meetingIds.length) throw new BadRequestException('Invalid meeting selection'); const member=await this.prisma.member.findUnique({where:{id:memberId}}); if(!member||member.status!==MemberStatus.ACTIVE) throw new ForbiddenException('Only active members can submit availability'); const cycle=await this.prisma.weeklyAvailabilityCycle.findUnique({where:{weekStart:this.weekStart()}}); if(!cycle) throw new NotFoundException('Weekly availability has not opened'); if(cycle.state!==WeeklyAvailabilityState.OPEN||new Date()>=cycle.closesAt) throw new ForbiddenException('The availability response window is closed'); const meetings=await this.weekMeetings(cycle.weekStart); const allowed=new Set(meetings.map(x=>x.id)); if(meetingIds.some(id=>!allowed.has(id))) throw new BadRequestException('A selected meeting is not eligible for this week'); return this.prisma.$transaction(async tx=>{ await tx.weeklyAvailabilityResponse.upsert({where:{cycleId_memberId:{cycleId:cycle.id,memberId}},update:{submittedAt:new Date()},create:{cycleId:cycle.id,memberId}}); await tx.memberServiceCommitment.deleteMany({where:{cycleId:cycle.id,memberId}}); if(meetingIds.length) await tx.memberServiceCommitment.createMany({data:meetingIds.map(meetingId=>({cycleId:cycle.id,memberId,meetingId,status:'COMMITTED'}))}); return {cycleId:cycle.id,selectedMeetingIds:meetingIds}; }); }
  async finalizeDue(now=new Date()) { const cycles=await this.prisma.weeklyAvailabilityCycle.findMany({where:{state:WeeklyAvailabilityState.OPEN,closesAt:{lte:now}}}); for(const cycle of cycles) await this.prisma.weeklyAvailabilityCycle.updateMany({where:{id:cycle.id,state:WeeklyAvailabilityState.OPEN},data:{state:WeeklyAvailabilityState.FINALIZED,finalizedAt:now}}); return cycles.length; }
  private weekMeetings(weekStart: Date) { const end=new Date(weekStart); end.setUTCDate(end.getUTCDate()+7); return this.prisma.meeting.findMany({where:{status:MeetingStatus.SCHEDULED,startTime:{gte:weekStart,lt:end}},orderBy:{startTime:'asc'},select:{id:true,title:true,startTime:true,endTime:true,locationName:true}}); }
}
