'use client';
import { useEffect, useState } from 'react';
import { Navbar } from '../../../../components/Navbar';
import { fetchApi } from '../../../../lib/api';
import { ChangePasswordCard } from '../../../../components/ChangePasswordCard';
const labels: Record<string,string> = {earlyPoints:'Early points',onTimePoints:'On-time points',gracePeriodPoints:'Grace-period points',latePoints:'Late points',absentPoints:'Absent points',excusedPoints:'Excused points',attendanceWeight:'Attendance weight (0–1)',punctualityWeight:'Punctuality weight (0–1)',followUpAbsences:'Consecutive absences for follow-up',warningAbsences:'Total absences for warning',reviewAttendanceBelow:'Attendance review threshold (%)',minimumMeetings:'Minimum meetings before review',rewardAttendance:'Recognition attendance threshold (%)',rewardPunctuality:'Recognition punctuality threshold (%)'};
export default function SettingsPage() {
 const [recognition,setRecognition]=useState<any>(null);
 useEffect(()=>{fetchApi('/scoring/recognition').then(setRecognition).catch(()=>{});},[]);
 const [policy,setPolicy]=useState<Record<string,number>|null>(null);const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
 useEffect(()=>{fetchApi('/reports/settings').then(setPolicy).catch(e=>setMessage(e.message));},[]);
 return <div className="min-h-screen bg-slate-950 text-white"><Navbar/><main className="max-w-3xl mx-auto p-6 space-y-5"><section className="space-y-3"><h1 className="text-2xl font-bold">Your account</h1><ChangePasswordCard variant="dark"/></section><h1 className="text-2xl font-bold">Scoring and follow-up settings</h1><p>Point changes apply to new attendance entries and reviewed corrections. Existing points remain recorded. Leaderboard weights and follow-up thresholds apply when recalculated.</p>{message&&<p role="status">{message}</p>}{policy&&<form className="grid sm:grid-cols-2 gap-4" onSubmit={async e=>{e.preventDefault();setSaving(true);try{setPolicy(await fetchApi('/reports/settings',{method:'PUT',body:JSON.stringify(policy)}));setMessage('Settings saved');}catch(err:any){setMessage(err.message);}finally{setSaving(false);}}}>{Object.entries(labels).map(([key,label])=><label key={key}>{label}<input className="block w-full rounded bg-slate-800 p-3" type="number" step="any" required value={policy[key]} onChange={e=>setPolicy({...policy,[key]:Number(e.target.value)})}/></label>)}<button disabled={saving} className="rounded bg-indigo-600 p-3">{saving?'Saving…':'Save settings'}</button></form>}<section className="space-y-3"><h2 className="text-xl font-bold">Members eligible for recognition</h2><button className="underline" onClick={()=>fetchApi('/scoring/recognition').then(setRecognition).catch(e=>setMessage(e.message))}>Refresh eligibility</button>{recognition?.members.length === 0 && <p>No members meet the current criteria.</p>}<ul>{recognition?.members.map((m:any)=><li key={m.memberId}>{m.firstName} {m.lastName} — {m.attendanceRate}% attendance, {m.punctualityRate}% punctuality</li>)}</ul></section></main></div>;
}
