import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { useAuth } from '../../src/state/auth-context';
import { api } from '../../src/services/api';

type Profile = { firstName:string; middleName?:string|null; lastName:string; preferredName?:string|null; phoneNumber:string; alternatePhoneNumber?:string|null; address?:string|null; dateOfBirth?:string|null; user?:{email:string}; celebrations?: {type:string; date:string}[] };
const dateOnly=(value?:string|null)=>value ? value.slice(0,10) : '';
export default function ProfileScreen(){
  const {signOut}=useAuth(); const [profile,setProfile]=useState<Profile|null>(null); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  const load=useCallback(async()=>{try{setError('');setProfile(await api<Profile>('/members/me/profile'));}catch(e:any){setError(e.message)}} ,[]);
  useEffect(()=>{load()},[load]);
  const update=(key:keyof Profile,value:string)=>setProfile(p=>p?{...p,[key]:value}:p);
  const save=async()=>{if(!profile)return; if(!profile.firstName.trim()||!profile.lastName.trim()||!profile.phoneNumber.trim()){setError('First name, last name, and phone number are required.');return} try{setSaving(true);setError('');const saved=await api<Profile>('/members/me/profile',{method:'PUT',body:JSON.stringify({firstName:profile.firstName,lastName:profile.lastName,middleName:profile.middleName,preferredName:profile.preferredName,phoneNumber:profile.phoneNumber,alternatePhoneNumber:profile.alternatePhoneNumber,address:profile.address,dateOfBirth:profile.dateOfBirth||undefined,celebrations:profile.celebrations?.map(c=>({type:c.type,date:dateOnly(c.date)}))})});setProfile(saved);Alert.alert('Profile updated','Your TFHC member profile has been saved.')}catch(e:any){setError(e.message)}finally{setSaving(false)}};
  if(!profile&&!error)return <View style={styles.center}><ActivityIndicator color="#0b1c30"/></View>;
  return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>My profile</Text><Text style={styles.hint}>Keep your contact and celebration details current. Your sign-in email is managed through Google.</Text>{error?<Text style={styles.error}>{error}</Text>:null}
  {profile?<View style={styles.card}><Field label="First name" value={profile.firstName} onChange={v=>update('firstName',v)}/><Field label="Middle name" value={profile.middleName??''} onChange={v=>update('middleName',v)}/><Field label="Last name" value={profile.lastName} onChange={v=>update('lastName',v)}/><Field label="Preferred name" value={profile.preferredName??''} onChange={v=>update('preferredName',v)}/><Field label="Email" value={profile.user?.email??''} editable={false}/><Field label="Phone" value={profile.phoneNumber} keyboardType="phone-pad" onChange={v=>update('phoneNumber',v)}/><Field label="Alternate phone" value={profile.alternatePhoneNumber??''} keyboardType="phone-pad" onChange={v=>update('alternatePhoneNumber',v)}/><Field label="Date of birth (YYYY-MM-DD)" value={dateOnly(profile.dateOfBirth)} onChange={v=>update('dateOfBirth',v)}/><Field label="Address" value={profile.address??''} onChange={v=>update('address',v)} multiline/><Pressable style={styles.primary} disabled={saving} onPress={save}><Text style={styles.primaryText}>{saving?'Saving…':'Save profile'}</Text></Pressable></View>:<Pressable style={styles.retry} onPress={load}><Text>Try again</Text></Pressable>}
  <Pressable style={styles.signout} onPress={async()=>{await signOut();router.replace('/login')}}><Text style={styles.signoutText}>Sign out</Text></Pressable></ScrollView>}
function Field({label,value,onChange,editable=true,keyboardType,multiline}:{label:string;value:string;onChange?:(v:string)=>void;editable?:boolean;keyboardType?:any;multiline?:boolean}){return <View><Text style={styles.label}>{label}</Text><TextInput style={[styles.input,multiline&&styles.multiline]} value={value} editable={editable} keyboardType={keyboardType} multiline={multiline} onChangeText={onChange}/></View>}
const styles=StyleSheet.create({page:{padding:20,backgroundColor:'#f8f9ff',gap:14},center:{flex:1,alignItems:'center',justifyContent:'center'},title:{fontSize:26,fontWeight:'800',color:'#0b1c30'},hint:{color:'#555b65',lineHeight:20},card:{backgroundColor:'#fff',padding:18,borderRadius:16,gap:12},label:{fontSize:13,fontWeight:'700',color:'#293848',marginBottom:5},input:{borderWidth:1,borderColor:'#d6dbe2',borderRadius:9,padding:11,color:'#0b1c30',backgroundColor:'#fff'},multiline:{minHeight:80,textAlignVertical:'top'},primary:{backgroundColor:'#0b1c30',borderRadius:10,padding:14,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'800'},signout:{borderWidth:1,borderColor:'#c6c6cd',padding:14,borderRadius:10,alignItems:'center'},signoutText:{fontWeight:'700',color:'#0b1c30'},error:{color:'#a12525',backgroundColor:'#fff0f0',padding:12,borderRadius:9},retry:{padding:15,alignItems:'center',borderWidth:1,borderColor:'#c6c6cd',borderRadius:9}});
